"""Walking-skeleton project writer.

Phase 2 hardcodes a single profile (standalone+Postgres). The writer copies
a static template tree from ``ignition_stack/templates/standalone-postgres/``
into the target directory and produces a ``.env`` from
:class:`~ignition_stack.config.schema.ProjectConfig`.

Every file is written in binary with explicit ``\\n`` newlines so the output
is byte-identical on Linux, macOS, and Windows. ``docker-bootstrap.sh`` in
particular must be LF-only or bash inside the container chokes on CR bytes.

Phase 4 generalizes this into the anchor-preserving Jinja2 + ruamel pipeline.
"""

from __future__ import annotations

from importlib import resources
from importlib.resources.abc import Traversable
from pathlib import Path

from ignition_stack.config.schema import ProjectConfig

_TEMPLATE_PACKAGE = "ignition_stack.templates"
_TEMPLATE_PROFILE = "standalone-postgres"


def write_project(config: ProjectConfig, target_dir: Path) -> list[Path]:
    """Generate the project tree at ``target_dir``.

    Returns the list of files written (absolute paths), in the order they
    were written. Raises :class:`FileExistsError` if ``target_dir`` already
    has files (refuses to clobber).
    """
    target_dir = Path(target_dir).resolve()
    if target_dir.exists() and any(target_dir.iterdir()):
        raise FileExistsError(
            f"target directory '{target_dir}' is not empty; refusing to overwrite"
        )
    target_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    # Copy the static template tree verbatim. Walks the package-data tree so
    # this works whether the install is editable or from a wheel.
    template_root = _template_root()
    for src_rel, content in _walk_template(template_root):
        dst = target_dir / src_rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_bytes(content)
        if src_rel.endswith("docker-bootstrap.sh"):
            dst.chmod(0o755)
        written.append(dst)

    # Render the .env from the resolved config.
    env_path = target_dir / ".env"
    env_path.write_bytes(_render_env(config).encode("utf-8"))
    written.append(env_path)

    return written


def _template_root() -> Traversable:
    # Navigate from a parent package whose name is a valid Python identifier
    # into the hyphenated profile directory. ``files()`` returns a Traversable
    # that supports ``/`` even for non-identifier subpath segments.
    return resources.files(_TEMPLATE_PACKAGE) / _TEMPLATE_PROFILE


def _walk_template(root: Traversable, prefix: str = "") -> list[tuple[str, bytes]]:
    """Yield (relative-path, bytes) for every file under ``root``.

    Skips Python package markers (``__init__.py``) and any pyc artifacts so
    the generated project doesn't contain Python plumbing.
    """
    out: list[tuple[str, bytes]] = []
    for entry in sorted(root.iterdir(), key=lambda e: e.name):
        name = entry.name
        rel = f"{prefix}{name}"
        if entry.is_dir():
            out.extend(_walk_template(entry, prefix=f"{rel}/"))
            continue
        if name == "__init__.py" or name.endswith(".pyc"):
            continue
        out.append((rel, entry.read_bytes()))
    return out


def _render_env(config: ProjectConfig) -> str:
    """Render the project .env. Always LF-terminated, no Windows surprises."""
    lines = [
        "# Generated by ignition-stack. Edit values, do not delete keys.",
        f"COMPOSE_PROJECT_NAME={config.name}",
        f"GATEWAY_NAME={config.name}",
        f"GATEWAY_HTTP_PORT={config.gateway_http_port}",
        f"IGNITION_IMAGE={config.ignition_image}",
        f"POSTGRES_IMAGE={config.postgres_image}",
        f"ADMIN_USERNAME={config.admin_username}",
        f"ADMIN_PASSWORD={config.admin_password}",
        f"DB_USER={config.db_user}",
        f"DB_PASSWORD={config.db_password}",
        f"TZ={config.timezone}",
    ]
    return "\n".join(lines) + "\n"
