"""Lifecycle record: every generated project's serialized resolved config.

Each project keeps a copy of its resolved
:class:`~ignition_stack.config.schema.ProjectConfig` under
``.ignition-stack/config.json``. That record is the one primitive ``reset`` and
``switch-arch`` need: they read it back, optionally reshape it, and re-run
generation - no second trip through the wizard.

The record is just the declarative config artifact (see
:mod:`ignition_stack.config.io`) written to a known path; ``init -f <file>``
consumes the identical format. ``read_record`` is a thin wrapper over
``load_config`` that reports a missing record as a :class:`LifecycleError` so
``reset`` / ``switch-arch`` can fail cleanly on a directory that was never
generated by this CLI.
"""

from __future__ import annotations

from pathlib import Path

from ignition_stack.config.io import ConfigIOError, dump_config, load_config
from ignition_stack.config.schema import ProjectConfig

# The directory the record lives in, at the project root. Dot-prefixed so it
# stays out of the way of the hand-readable compose/.env/Makefile tree.
LIFECYCLE_DIR = ".ignition-stack"
RECORD_NAME = "config.json"


class LifecycleError(Exception):
    """Raised when a lifecycle operation can't find or read its record."""


def record_path(project_dir: Path) -> Path:
    """Where the recorded config lives for a project rooted at ``project_dir``."""
    return Path(project_dir) / LIFECYCLE_DIR / RECORD_NAME


def has_record(project_dir: Path) -> bool:
    """True when ``project_dir`` carries a lifecycle record."""
    return record_path(project_dir).is_file()


def write_record(config: ProjectConfig, project_dir: Path) -> Path:
    """Persist ``config`` as the project's recorded config. Returns its path.

    The record is the *resolved* config as JSON (the caller passes the same
    object it handed to the writer); :func:`read_record` reproduces it exactly.
    """
    dst = record_path(project_dir)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_bytes(dump_config(config, "json").encode("utf-8"))
    return dst


def read_record(project_dir: Path) -> ProjectConfig:
    """Load the recorded config for a project.

    Raises :class:`LifecycleError` when the project has no record (a directory
    that was never generated by this CLI, or one whose record was removed) or
    when the record can't be parsed or validated.
    """
    src = record_path(project_dir)
    if not src.is_file():
        raise LifecycleError(
            f"no lifecycle record at {src}. This directory was not generated by "
            "ignition-stack (or its record was removed); reset/switch-arch "
            "need a project with a recorded config."
        )
    try:
        return load_config(src)
    except ConfigIOError as exc:
        raise LifecycleError(str(exc)) from exc
