import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Explicit sidebar (not autogenerated) so ordering and the category landing
// pages stay deterministic as content is added.
const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    {
      type: "category",
      label: "Architecture profiles",
      link: { type: "doc", id: "profiles/index" },
      items: [
        "profiles/standalone",
        "profiles/scaleout",
        "profiles/hub-and-spoke",
        "profiles/mcp-n8n",
      ],
    },
    {
      type: "category",
      label: "Services",
      link: { type: "doc", id: "services/index" },
      items: [
        "services/postgres",
        "services/mysql",
        "services/mariadb",
        "services/mongo",
        "services/keycloak",
        "services/chariot",
        "services/hivemq",
        "services/emqx",
        "services/rabbitmq",
        "services/kafka",
        "services/opcua-sim",
        "services/modbus-sim",
        "services/n8n",
      ],
    },
    {
      type: "category",
      label: "How it works",
      collapsed: false,
      items: ["architecture/how-generation-works", "lifecycle/modes", "lifecycle/cleanup"],
    },
    {
      type: "category",
      label: "Reference",
      items: ["reference/cli", "reference/seeding-matrix"],
    },
    {
      type: "category",
      label: "Maintainer guides",
      items: ["maintainers/adding-a-service", "maintainers/updating-modules"],
    },
  ],
};

export default sidebars;
