import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Explicit sidebar (not autogenerated) so ordering and the category landing
// pages stay deterministic as content is added.
const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      items: ["get-started/installation", "get-started/quickstart"],
    },
    {
      type: "category",
      label: "Concepts",
      items: [
        "concepts/how-generation-works",
        "concepts/seeding",
        "concepts/lifecycle-modes",
      ],
    },
    {
      type: "category",
      label: "Architecture profiles",
      link: { type: "doc", id: "profiles/index" },
      items: [
        "profiles/standalone",
        "profiles/scaleout",
        "profiles/hub-and-spoke",
        "profiles/mcp-n8n",
      ],
    },
    {
      type: "category",
      label: "Services",
      link: { type: "doc", id: "services/index" },
      items: [
        {
          type: "category",
          label: "Databases",
          items: [
            "services/postgres",
            "services/mysql",
            "services/mariadb",
            "services/mongo",
          ],
        },
        {
          type: "category",
          label: "MQTT brokers",
          items: [
            "services/chariot",
            "services/hivemq",
            "services/emqx",
            "services/rabbitmq",
          ],
        },
        {
          type: "category",
          label: "Streaming",
          items: ["services/kafka"],
        },
        {
          type: "category",
          label: "Identity",
          items: ["services/keycloak"],
        },
        {
          type: "category",
          label: "Simulators",
          items: ["services/opcua-sim", "services/modbus-sim"],
        },
        {
          type: "category",
          label: "Automation",
          items: ["services/n8n"],
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      items: ["guides/reset-and-reshape", "guides/teardown"],
    },
    {
      type: "category",
      label: "Reference",
      items: ["reference/cli", "reference/seeding-matrix"],
    },
    {
      type: "category",
      label: "Contribute",
      items: [
        "contribute/add-a-service",
        "contribute/update-module-versions",
        "contribute/ci",
        "contribute/releasing",
      ],
    },
  ],
};

export default sidebars;
